### ISSUE TITLE
why there is no source code available 

### ISSUE THREAD

**Issue by pras2020** [torrvision/ELAS_SoC#1]
Hello team 

I went through your paper and i came to this link through the paper.I couldnt see the source code here. Please share the source code which will be really helpfull.

**Comment by seakros** [comment]
Hi Pras2020,
We're just cleaning up the code/making it more legible before hosting it up here - hopefully be up in the next few days!

**Comment by pras2020** [comment]
can you people share me the code, so that i can work around it asap .

**Comment by seakros** [comment]
Hi Pras2020,
I've uploaded the code as is to get it out faster, but it still need a little bit more tidying/commenting to make it more clear. This version of the code does not require OpenCV so you don't have to worry about cross-compiling it for the ARM CPU or anything. Just open an SDx/SDSoC project, import the files, mark the functions for acceleration and build the solution.
best,
Oscar
